//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class KODX
    {
        public string KODID { get; set; }
        public short NVALUKOD { get; set; }
        public Nullable<short> CSTATKOD { get; set; }
        public string TDESCTUR { get; set; }
        public string TDESCENG { get; set; }
        public Nullable<short> NSORTKOD { get; set; }
        public string TMNEMKOD { get; set; }
        public Nullable<System.DateTime> DRECDGEN { get; set; }
        public string TUSERGEN { get; set; }
        public Nullable<System.DateTime> DMODIKOD { get; set; }
        public string TMODIKOD { get; set; }
        public string TCODEKOD { get; set; }
    }
}
