//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LidyaEntities : DbContext
    {
        public LidyaEntities()
            : base("name=LidyaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KODX> KODX { get; set; }
        public DbSet<TCARTLIST> TCARTLIST { get; set; }
        public DbSet<TITEMLIST> TITEMLIST { get; set; }
        public DbSet<TMEDIALIST> TMEDIALIST { get; set; }
        public DbSet<TMEDIASIZE> TMEDIASIZE { get; set; }
        public DbSet<TRITMREYON> TRITMREYON { get; set; }
        public DbSet<TRUSERITEM> TRUSERITEM { get; set; }
        public DbSet<TSUPPLIER> TSUPPLIER { get; set; }
        public DbSet<TADDRLIST> TADDRLIST { get; set; }
        public DbSet<TCARTITMLIST> TCARTITMLIST { get; set; }
        public DbSet<TGREYON> TGREYON { get; set; }
        public DbSet<TMSGMASTER> TMSGMASTER { get; set; }
        public DbSet<TMSGQUEUE> TMSGQUEUE { get; set; }
        public DbSet<TMSGTEMPLATE> TMSGTEMPLATE { get; set; }
        public DbSet<TINTLOG> TINTLOG { get; set; }
        public DbSet<TSREYON> TSREYON { get; set; }
        public DbSet<TUSERLIST> TUSERLIST { get; set; }
        public DbSet<TCCTICKET> TCCTICKET { get; set; }
        public DbSet<TMEDIAQUEUE> TMEDIAQUEUE { get; set; }
        public DbSet<TCARTPYMNT> TCARTPYMNT { get; set; }
        public DbSet<TRYNMAP> TRYNMAP { get; set; }
    }
}
