//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TADDRLIST
    {
        public TADDRLIST()
        {
            this.TCARTLIST = new HashSet<TCARTLIST>();
            this.TCARTLIST1 = new HashSet<TCARTLIST>();
        }
    
        public decimal ADDRID { get; set; }
        public string USRID { get; set; }
        public string TADDRTYPE { get; set; }
        public string TPHONERCPT { get; set; }
        public string TNAMERCPT { get; set; }
        public string TUNIQUEID { get; set; }
        public string TADDRLINE1 { get; set; }
        public string TADDRLINE2 { get; set; }
        public string TCOUNCODE { get; set; }
        public string TCOUNTRY { get; set; }
        public Nullable<long> CITYID { get; set; }
        public string TCITY { get; set; }
        public Nullable<long> TOWNID { get; set; }
        public string TTOWN { get; set; }
        public string TZIPCODE { get; set; }
        public Nullable<decimal> CSTATADDR { get; set; }
        public Nullable<System.DateTime> DRECDGEN { get; set; }
        public Nullable<System.DateTime> DMODIADDR { get; set; }
        public string TEMAIL { get; set; }
    
        public virtual ICollection<TCARTLIST> TCARTLIST { get; set; }
        public virtual ICollection<TCARTLIST> TCARTLIST1 { get; set; }
        public virtual TUSERLIST TUSERLIST { get; set; }
    }
}
