//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCARTPYMNT
    {
        public decimal CARTID { get; set; }
        public decimal SUPID { get; set; }
        public string TCOMPANY { get; set; }
        public Nullable<decimal> NORDERAMNT { get; set; }
        public decimal NINST { get; set; }
        public Nullable<short> NINSTRATE { get; set; }
        public Nullable<decimal> NTOTALPROD { get; set; }
        public Nullable<decimal> NLIMCARGO { get; set; }
        public Nullable<decimal> NCARGOAMNT { get; set; }
        public Nullable<decimal> NTOTALAMNT { get; set; }
        public Nullable<decimal> NCARGOPYMT { get; set; }
        public Nullable<decimal> NCASHPYMT { get; set; }
        public Nullable<decimal> NLDYPYMT { get; set; }
        public Nullable<decimal> NTOTALPYMNT { get; set; }
        public Nullable<decimal> NCRDPYMT { get; set; }
        public Nullable<decimal> NBNKCOST { get; set; }
        public Nullable<decimal> NBNKRCVD { get; set; }
        public Nullable<decimal> NCOLLECTED { get; set; }
        public Nullable<decimal> NTOTALVAT { get; set; }
        public Nullable<decimal> NLWMARGIN { get; set; }
        public Nullable<decimal> NLWINCOME { get; set; }
        public Nullable<decimal> NSUPPYMT { get; set; }
        public string TMODIUSR { get; set; }
        public Nullable<System.DateTime> DMODIDATE { get; set; }
        public Nullable<short> CTYPEPYMT { get; set; }
        public Nullable<short> CSTATPYMT { get; set; }
        public Nullable<System.DateTime> DDATEPYMT { get; set; }
        public Nullable<short> BMAILSENT { get; set; }
        public Nullable<short> NTRYCOUNT { get; set; }
        public Nullable<decimal> NLWCOMVAT { get; set; }
        public string TINVINFO { get; set; }
        public Nullable<System.DateTime> DDATEINV { get; set; }
        public Nullable<System.DateTime> DDATEDLV { get; set; }
        public string TREFNTRX { get; set; }
        public Nullable<System.DateTime> DBNKPYMT { get; set; }
        public string TBANKDESC { get; set; }
        public string TIBAN { get; set; }
        public string TBANKREF { get; set; }
        public Nullable<decimal> NCASHITMPYMT { get; set; }
        public Nullable<decimal> NLDYITMPYMT { get; set; }
        public Nullable<decimal> NDEDUCTAMNT { get; set; }
        public string TDESCDEDUCT { get; set; }
        public Nullable<decimal> NRETAMNT { get; set; }
    
        public virtual TCARTLIST TCARTLIST { get; set; }
        public virtual TSUPPLIER TSUPPLIER { get; set; }
    }
}
