//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCARTITMLIST
    {
        public decimal CARTITMID { get; set; }
        public Nullable<decimal> CARTID { get; set; }
        public Nullable<long> DEALID { get; set; }
        public Nullable<decimal> STRID { get; set; }
        public string USRID { get; set; }
        public Nullable<long> ITMID { get; set; }
        public Nullable<decimal> NQTY { get; set; }
        public Nullable<decimal> NPRICUIR { get; set; }
        public Nullable<decimal> NINIPITM { get; set; }
        public Nullable<decimal> NTERMAMNT { get; set; }
        public Nullable<decimal> NITMAMNT { get; set; }
        public Nullable<decimal> NCOUPON { get; set; }
        public Nullable<decimal> NCASHPYMT { get; set; }
        public Nullable<decimal> NLDYPYMT { get; set; }
        public Nullable<decimal> NCARGOAMNT { get; set; }
        public string TREFNTRX { get; set; }
        public Nullable<System.DateTime> DRECDATE { get; set; }
        public Nullable<decimal> NVAT { get; set; }
        public string TNOTE { get; set; }
        public Nullable<decimal> CSTATINT { get; set; }
        public string TSUPORDERID { get; set; }
        public string TCANCELMSG { get; set; }
        public Nullable<System.DateTime> DDATECANCEL { get; set; }
        public string TMODIUSR { get; set; }
        public string TCARGOINFO { get; set; }
        public Nullable<decimal> NPROFIT { get; set; }
        public Nullable<decimal> NADVANTAGE { get; set; }
        public Nullable<long> FROMSTRID { get; set; }
        public Nullable<decimal> RETCARTITMID { get; set; }
        public Nullable<System.DateTime> DMODIDATE { get; set; }
        public Nullable<System.DateTime> DAPPDATE { get; set; }
        public Nullable<decimal> NLDYBUYER { get; set; }
        public Nullable<decimal> NCOMSELLER { get; set; }
        public Nullable<decimal> BMAILSENT { get; set; }
        public Nullable<decimal> NTRYCOUNT { get; set; }
        public Nullable<decimal> NRETAMNT { get; set; }
        public Nullable<decimal> NRETQTY { get; set; }
        public Nullable<decimal> NDISCOUNT { get; set; }
    
        public virtual TCARTLIST TCARTLIST { get; set; }
        public virtual TRUSERITEM TRUSERITEM { get; set; }
        public virtual TITEMLIST TITEMLIST { get; set; }
        public virtual TUSERLIST TUSERLIST { get; set; }
    }
}
