//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCCTICKET
    {
        public decimal TICKETID { get; set; }
        public string TCCTICKETID { get; set; }
        public string TCCUSER { get; set; }
        public Nullable<System.DateTime> DCCDATE { get; set; }
        public Nullable<System.DateTime> DCREATEDON { get; set; }
        public string TTOPICCODE { get; set; }
        public string TTOPIC { get; set; }
        public string TDESCRIPTION { get; set; }
        public Nullable<decimal> NPRIORITY { get; set; }
        public Nullable<decimal> CSTATISSUE { get; set; }
        public Nullable<System.DateTime> DMODIFYON { get; set; }
        public string TASSIGNEE { get; set; }
        public string TRESOLUTION { get; set; }
        public Nullable<System.DateTime> DRESOLUTIONTARGET { get; set; }
        public Nullable<System.DateTime> DRESOLUTION { get; set; }
        public Nullable<decimal> ORDERID { get; set; }
        public string TCUSTNAME { get; set; }
        public string TCUSTUSRID { get; set; }
        public string TCUSTPHONE { get; set; }
        public string TCUSTMAIL { get; set; }
        public Nullable<decimal> SUPID { get; set; }
        public Nullable<decimal> ITMID { get; set; }
        public string TPRODUCTID { get; set; }
        public string TPRODCODE { get; set; }
        public string TCUSTTOWN { get; set; }
        public string TCUSTCITY { get; set; }
        public string TCARGOCOMPANY { get; set; }
        public string TCARGOTRACKID { get; set; }
    }
}
