//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGREYON
    {
        public TGREYON()
        {
            this.TGREYON1 = new HashSet<TGREYON>();
            this.TRITMREYON = new HashSet<TRITMREYON>();
        }
    
        public decimal GRYID { get; set; }
        public Nullable<decimal> CCATGITM { get; set; }
        public string TDESCTUR { get; set; }
        public string TDESCENG { get; set; }
        public string TIMAGE { get; set; }
        public string TIMAGE2 { get; set; }
        public string TIMAGE3 { get; set; }
        public string TIMAGE4 { get; set; }
        public Nullable<decimal> PARID { get; set; }
        public Nullable<decimal> NLEVEL { get; set; }
        public Nullable<decimal> CSTATGRY { get; set; }
        public Nullable<decimal> BIMGCHG { get; set; }
        public string TQRYSTR { get; set; }
        public Nullable<short> NSORTORDER { get; set; }
        public Nullable<decimal> NIMGVERSION { get; set; }
        public string TPATH { get; set; }
    
        public virtual ICollection<TGREYON> TGREYON1 { get; set; }
        public virtual TGREYON TGREYON2 { get; set; }
        public virtual ICollection<TRITMREYON> TRITMREYON { get; set; }
    }
}
