//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTLOG
    {
        public System.DateTime DLOGDATE { get; set; }
        public string USRID { get; set; }
        public string TNAME { get; set; }
        public string TLOGDATA { get; set; }
        public Nullable<decimal> CTYPELOG { get; set; }
    }
}
