//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMLIST
    {
        public TITEMLIST()
        {
            this.TRITMREYON = new HashSet<TRITMREYON>();
            this.TCARTITMLIST = new HashSet<TCARTITMLIST>();
        }
    
        public long ITMID { get; set; }
        public string TDESCTUR { get; set; }
        public string TDESCENG { get; set; }
        public Nullable<decimal> LAST_PRICE { get; set; }
        public Nullable<System.DateTime> LAST_PRICE_DATE { get; set; }
        public Nullable<decimal> CCATGITM { get; set; }
        public Nullable<short> CUNITITM { get; set; }
        public Nullable<decimal> PREV_PRICE { get; set; }
        public Nullable<short> CTYPEITM { get; set; }
        public Nullable<System.DateTime> DLAUNITM { get; set; }
        public Nullable<decimal> NINIPITM { get; set; }
        public Nullable<int> NLIFEITM { get; set; }
        public Nullable<decimal> NMINPITM { get; set; }
        public Nullable<decimal> NMAXPITM { get; set; }
        public Nullable<long> NADETITM { get; set; }
        public string TBRANDNAME { get; set; }
        public string TPRODCODE { get; set; }
        public string TPRODUCTID { get; set; }
        public string TMODELID { get; set; }
        public string TMODELSIZE { get; set; }
        public Nullable<decimal> NCOGSITM { get; set; }
        public Nullable<decimal> SUPID { get; set; }
        public Nullable<short> BFIXPITM { get; set; }
        public Nullable<decimal> NITMGRPID { get; set; }
        public string TSPEC1 { get; set; }
        public string TSPEC2 { get; set; }
        public string TSPEC3 { get; set; }
        public Nullable<decimal> NITMFAMID { get; set; }
        public Nullable<short> CSTATITM { get; set; }
        public Nullable<System.DateTime> DGENEITM { get; set; }
        public string TGENEITM { get; set; }
        public Nullable<System.DateTime> DMODIITM { get; set; }
        public string TMODIITM { get; set; }
        public Nullable<decimal> SR3ID { get; set; }
        public Nullable<short> BSYNCREQ { get; set; }
        public Nullable<decimal> NVAT { get; set; }
        public string TCOLGRP { get; set; }
        public string TMODELCOLOR { get; set; }
        public Nullable<long> TCOLGRPID { get; set; }
        public string TDESC { get; set; }
        public Nullable<decimal> NDLVDAYS { get; set; }
        public Nullable<decimal> NNOTESIZE { get; set; }
        public Nullable<decimal> NQTYLIMIT { get; set; }
        public Nullable<decimal> NINSTPITM { get; set; }
        public Nullable<decimal> BDEFITM { get; set; }
        public Nullable<decimal> TTHUMBID { get; set; }
    
        public virtual TSUPPLIER TSUPPLIER { get; set; }
        public virtual ICollection<TRITMREYON> TRITMREYON { get; set; }
        public virtual ICollection<TCARTITMLIST> TCARTITMLIST { get; set; }
        public virtual TSREYON TSREYON { get; set; }
    }
}
