//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMEDIASIZE
    {
        public decimal MSID { get; set; }
        public decimal WIDTH { get; set; }
        public decimal HEIGHT { get; set; }
        public decimal ISACTIVE { get; set; }
        public string TITLE { get; set; }
        public decimal QUALITY { get; set; }
        public string FORMAT { get; set; }
        public decimal MEDIATYPE { get; set; }
        public string FILENAME { get; set; }
        public decimal SIZENO { get; set; }
        public string BUCKETNAME { get; set; }
        public string BUCKETFOLDER { get; set; }
    }
}
