//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMEDIAQUEUE
    {
        public decimal MDYQID { get; set; }
        public string URL { get; set; }
        public decimal MEDIATYPE { get; set; }
        public Nullable<decimal> SRYID { get; set; }
        public Nullable<decimal> ISUPLOADED { get; set; }
        public Nullable<decimal> UPLOADTRIES { get; set; }
        public string TCOLGRP { get; set; }
        public decimal SUPID { get; set; }
        public decimal MEDIAORDER { get; set; }
        public Nullable<System.DateTime> DRECDATE { get; set; }
    }
}
