//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMEDIALIST
    {
        public decimal MDYID { get; set; }
        public decimal ENTITYID { get; set; }
        public decimal PACKNO { get; set; }
        public string MEDIAPATH { get; set; }
        public decimal ISDEFAULT { get; set; }
        public System.DateTime LASTSYNCTIME { get; set; }
        public decimal MEDIASIZE { get; set; }
        public decimal SUPID { get; set; }
        public decimal MEDIATYPE { get; set; }
        public Nullable<decimal> MDYQID { get; set; }
        public string TCOLGRP { get; set; }
    }
}
