//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMSGMASTER
    {
        public TMSGMASTER()
        {
            this.TMSGTEMPLATE = new HashSet<TMSGTEMPLATE>();
        }
    
        public decimal MSMID { get; set; }
        public string TDESC { get; set; }
        public string THTML { get; set; }
        public short BACTIVE { get; set; }
    
        public virtual ICollection<TMSGTEMPLATE> TMSGTEMPLATE { get; set; }
    }
}
