//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMSGQUEUE
    {
        public string TBODY { get; set; }
        public string TSUBJECT { get; set; }
        public string TMAILUSER { get; set; }
        public decimal TMSGQID { get; set; }
        public string TFRUSR { get; set; }
        public string TTOUSRS { get; set; }
        public short BISSENT { get; set; }
        public decimal NSENDTRIES { get; set; }
        public System.DateTime TGENEMSGQ { get; set; }
        public Nullable<System.DateTime> TSENTMSGQ { get; set; }
    }
}
