//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRITMREYON
    {
        public long ITMID { get; set; }
        public decimal GRYID { get; set; }
        public decimal SRYID { get; set; }
        public decimal BDFLTIRR { get; set; }
        public Nullable<decimal> CSTATIRR { get; set; }
        public Nullable<System.DateTime> DGENEIRR { get; set; }
        public string TGENEIRR { get; set; }
        public Nullable<System.DateTime> DMODIIRR { get; set; }
        public string TMODIIRR { get; set; }
        public Nullable<decimal> NSORTORDER { get; set; }
    
        public virtual TITEMLIST TITEMLIST { get; set; }
        public virtual TGREYON TGREYON { get; set; }
        public virtual TSREYON TSREYON { get; set; }
    }
}
