//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRYNMAP
    {
        public decimal GRYID { get; set; }
        public decimal SRYID { get; set; }
        public Nullable<System.DateTime> DMODIRYN { get; set; }
        public string TMODIRYN { get; set; }
    }
}
