//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSREYON
    {
        public TSREYON()
        {
            this.TITEMLIST = new HashSet<TITEMLIST>();
            this.TRITMREYON = new HashSet<TRITMREYON>();
        }
    
        public decimal SRYID { get; set; }
        public Nullable<decimal> CCATGITM { get; set; }
        public string TDESCTUR { get; set; }
        public string TDESCENG { get; set; }
        public string TIMAGE { get; set; }
        public string TIMAGE2 { get; set; }
        public string TIMAGE3 { get; set; }
        public string TIMAGE4 { get; set; }
        public Nullable<decimal> PARID { get; set; }
        public Nullable<decimal> NLEVEL { get; set; }
        public Nullable<decimal> SUPID { get; set; }
        public Nullable<decimal> GRYID { get; set; }
        public Nullable<short> CSTATSRY { get; set; }
        public Nullable<System.DateTime> DGENESRY { get; set; }
        public string TGENESRY { get; set; }
        public Nullable<System.DateTime> DMODISRY { get; set; }
        public string TMODISRY { get; set; }
        public string SCATID { get; set; }
        public string SPARID { get; set; }
        public Nullable<decimal> BIMGCHG { get; set; }
        public Nullable<decimal> NSORTORDER { get; set; }
        public Nullable<decimal> BSENSITIVE { get; set; }
        public Nullable<short> CTYPERYN { get; set; }
        public decimal NIMGVERSION { get; set; }
        public short BGRPBYCOL { get; set; }
        public string TPATH { get; set; }
    
        public virtual ICollection<TITEMLIST> TITEMLIST { get; set; }
        public virtual ICollection<TRITMREYON> TRITMREYON { get; set; }
    }
}
