//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lidya.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSUPPLIER
    {
        public TSUPPLIER()
        {
            this.TITEMLIST = new HashSet<TITEMLIST>();
            this.TCARTPYMNT = new HashSet<TCARTPYMNT>();
        }
    
        public decimal SUPID { get; set; }
        public string TSUPNAME { get; set; }
        public string TCOMPANY { get; set; }
        public string TADDRLINE1 { get; set; }
        public string TADDRLINE2 { get; set; }
        public string TTOWN { get; set; }
        public string TCITY { get; set; }
        public string TZIPCODE { get; set; }
        public string TPHONE { get; set; }
        public string TCONTACT { get; set; }
        public string TCNTPHONE { get; set; }
        public Nullable<decimal> AD1ID { get; set; }
        public Nullable<decimal> AD2ID { get; set; }
        public Nullable<decimal> SS0ID { get; set; }
        public Nullable<short> BUIDREQ { get; set; }
        public Nullable<decimal> CCATGITM { get; set; }
        public Nullable<decimal> CSTATMRCH { get; set; }
        public Nullable<decimal> NADVANTAGE { get; set; }
        public Nullable<decimal> CTYPEADV { get; set; }
        public Nullable<decimal> NACCITMID { get; set; }
        public Nullable<short> BFIXPITM { get; set; }
        public Nullable<decimal> CSTORETYPE { get; set; }
        public Nullable<decimal> NINVCOUNT { get; set; }
        public Nullable<decimal> NADVMGZ { get; set; }
        public Nullable<decimal> NFRNDADV { get; set; }
        public Nullable<decimal> SORTORDER { get; set; }
        public Nullable<decimal> NLIMCARGO { get; set; }
        public Nullable<decimal> NCARGOAMNT { get; set; }
        public Nullable<decimal> NPROFIT { get; set; }
        public Nullable<decimal> BCHRGBNK { get; set; }
        public string UNAME { get; set; }
        public string PASS { get; set; }
        public Nullable<decimal> NVAT { get; set; }
        public string TINTRO { get; set; }
        public Nullable<decimal> NPAYDAYS { get; set; }
        public string TXMLURL { get; set; }
        public string TCNTMAIL { get; set; }
        public string TTAXBUREAU { get; set; }
        public string TTAXNUMBER { get; set; }
        public string TTECHCNT { get; set; }
        public string TTECHPHONE { get; set; }
        public string TTECHMAIL { get; set; }
        public string TRETURNCNT { get; set; }
        public string TRETURNPHONE { get; set; }
        public string TRETURNMAIL { get; set; }
        public string TRETURNADDR1 { get; set; }
        public string TRETURNADDR2 { get; set; }
        public string TRETURNTOWN { get; set; }
        public string TRETURNCITY { get; set; }
        public string TRETURNZIP { get; set; }
        public string TCARGOCOMPANY1 { get; set; }
        public string TCARGOCOMPANY2 { get; set; }
        public string TCARGOCOMPANY3 { get; set; }
        public string TBANKNAME { get; set; }
        public string TBANKBRANCH { get; set; }
        public string TBANKACC { get; set; }
        public string TIBANCODE { get; set; }
        public Nullable<decimal> BCOMWITHVAT { get; set; }
    
        public virtual ICollection<TITEMLIST> TITEMLIST { get; set; }
        public virtual ICollection<TCARTPYMNT> TCARTPYMNT { get; set; }
    }
}
